//! `main.rs` + `lib.rs` scaffolding for generated user-projects.
//!
//! These are the entry-point files every user-project ships with — the
//! studio doesn't expect users to author them, but they live OUTSIDE
//! `@generated` regions (with the exception of the route-mount block
//! inside `lib.rs::router`) so users can extend startup behaviour with
//! their own middleware, env wiring, or graceful-shutdown logic.
//!
//! ## What's generated vs user-editable
//!
//! - `main.rs`: 100% generated. If the user wants startup hooks (e.g. a
//!   different listener config), they wrap `<crate>::router()` themselves
//!   in a separate binary; the studio's `main.rs` is a known-good default.
//! - `lib.rs`: skeleton is generated (module decls, the `router()` fn
//!   signature). The body of `router()` carries a `@generated:begin
//!   routes / @generated:end routes` region into which the `http.route`
//!   template splices `.route(...)` lines. Everything else in `lib.rs` is
//!   user-editable.
//!
//! ## No-panic discipline
//!
//! Generated `main.rs` uses `expect` only on unrecoverable startup
//! conditions (listener bind, server start). Consistent with the studio's
//! CLAUDE.md two-codebase rule applied to the generated side.

use crate::projects::Slug;

/// Generate the canonical `main.rs` for a user-project. Pure text; no
/// `@generated` regions (the whole file is regenerated each pass).
///
/// `spawn_tasks` is a list of Rust expressions that each evaluate to a
/// `Future<Output = ()>`. They are wrapped in `supervise()` and spawned
/// after the HTTP server is bound but before it is awaited.
pub fn main_rs(slug: &Slug, spawn_tasks: &[(String, String)]) -> String {
    let crate_name = slug.as_str().replace('-', "_");

    let spawn_lines = if spawn_tasks.is_empty() {
        String::new()
    } else {
        let mut s = "\n    // Long-running tasks\n".to_string();
        for (name, expr) in spawn_tasks {
            s.push_str(&format!(
                "    tokio::spawn(supervise(\"{name}\", || {expr}));\n"
            ));
        }
        s
    };

    let supervise_fn = if spawn_tasks.is_empty() {
        String::new()
    } else {
        r#"

/// Supervisor: restart a long-running task on panic with capped
/// exponential backoff.
async fn supervise<F, Fut>(name: &'static str, mut factory: F)
where
    F: FnMut() -> Fut + Send + 'static,
    Fut: std::future::Future<Output = ()> + Send + 'static,
{
    let mut backoff = std::time::Duration::from_secs(1);
    loop {
        tracing::info!(task = name, "starting");
        let task = tokio::spawn(factory());
        match task.await {
            Ok(()) => {
                tracing::warn!(task = name, "exited cleanly; restarting");
                backoff = std::time::Duration::from_secs(1);
            }
            Err(_) => {
                tracing::error!(task = name, "panicked; restarting after {:?} backoff", backoff);
                tokio::time::sleep(backoff).await;
                backoff = std::cmp::min(backoff * 2, std::time::Duration::from_secs(60));
            }
        }
    }
}
"#
        .to_string()
    };

    format!(
        r#"//! Generated by rust_no_code studio. This file is fully regenerated
//! on every `POST /api/projects/{slug}/regen` call. To customise startup,
//! either bring your own binary that calls `{crate_name}::router()` or
//! file a feature request to widen the template surface.

#[tokio::main]
async fn main() {{
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let addr = std::env::var("BIND_ADDR").unwrap_or_else(|_| "127.0.0.1:8080".to_string());
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .expect("failed to bind listener");
    tracing::info!(%addr, "{crate_name} listening");

    let app = {crate_name}::router();
    let server = axum::serve(listener, app);{spawn_lines}
    server.await.expect("server crashed");
}}
{supervise_fn}
"#,
        slug = slug.as_str(),
        crate_name = crate_name,
        spawn_lines = spawn_lines,
        supervise_fn = supervise_fn,
    )
}

/// Generate the canonical `errors.rs` for a user-project.
///
/// Introduced in Section 7. Provides a minimal `AppError` enum using
/// `thiserror` and an Axum `IntoResponse` impl so that handlers and
/// services can return `Result<T, AppError>` out of the box.
///
/// This file is fully regenerated each pass (no `@generated` regions in
/// v1) because error variants are typically appended, not replaced, and
/// the studio does not yet support mergeable error definitions.
pub fn errors_rs() -> String {
    r#"//! Application-level errors for this generated project.
//!
//! This file is fully regenerated on each `POST /api/projects/:slug/regen`.
//! To add custom error variants, either edit outside `@generated` regions
//! (if introduced in a later section) or manage your own error type in a
//! separate module.

use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use thiserror::Error;

/// The canonical error type returned by handlers and services.
#[derive(Debug, Error)]
pub enum AppError {
    #[error("not found")]
    NotFound,
    #[error("bad request: {0}")]
    BadRequest(String),
    #[error("internal server error")]
    Internal,
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let (status, body) = match self {
            AppError::NotFound => (StatusCode::NOT_FOUND, self.to_string()),
            AppError::BadRequest(_) => (StatusCode::BAD_REQUEST, self.to_string()),
            AppError::Internal => (StatusCode::INTERNAL_SERVER_ERROR, self.to_string()),
        };
        (status, body).into_response()
    }
}
"#
    .to_string()
}

/// Generate the `lib.rs` scaffold. The empty `@generated:begin routes`
/// region is the splice point T7's `http.route` template targets.
pub fn lib_rs(_slug: &Slug) -> String {
    r#"//! Generated by rust_no_code studio. The module declarations and the
//! `router()` function are regenerated each pass; user-edited code is
//! preserved outside the `@generated` regions.

#![allow(dead_code, unused_imports, unused_variables)]

// @generated:begin module_decls
// (Filled by codegen — module declarations live here.)
// @generated:end module_decls

/// HTTP router for this user-project. Routes mounted here are spliced
/// from `http.route` template emissions; add additional `.layer(...)`
/// middleware outside the `@generated:routes` region and your edits will
/// survive regen.
pub fn router() -> axum::Router {
    let r = axum::Router::new();
    // @generated:begin routes
    // (Filled by codegen — `.route(...)` calls live here.)
    // @generated:end routes
    r
}
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn slug(s: &str) -> Slug {
        Slug::new(s).unwrap()
    }

    #[test]
    fn test_main_rs_parses_as_rust() {
        let src = main_rs(&slug("user-service"), &[]);
        let err = syn::parse_file(&src).err();
        assert!(err.is_none(), "main.rs must be valid Rust: {err:?}");
    }

    #[test]
    fn test_main_rs_references_crate_name_with_dashes_replaced() {
        let src = main_rs(&slug("user-service"), &[]);
        assert!(src.contains("user_service::router()"));
        assert!(!src.contains("user-service::router()"));
    }

    #[test]
    fn test_main_rs_with_spawn_tasks_includes_supervise() {
        let tasks = vec![(
            "orders-consumer".to_string(),
            "crate::consumers::orders::run()".to_string(),
        )];
        let src = main_rs(&slug("svc"), &tasks);
        assert!(src.contains("async fn supervise"), "supervise helper must be present");
        assert!(src.contains("tokio::spawn(supervise(\"orders-consumer\""));
        assert!(src.contains("crate::consumers::orders::run()"));
        assert!(syn::parse_file(&src).is_ok(), "main.rs with spawns must parse");
    }

    #[test]
    fn test_main_rs_without_spawn_tasks_omits_supervise() {
        let src = main_rs(&slug("svc"), &[]);
        assert!(!src.contains("async fn supervise"));
    }

    #[test]
    fn test_lib_rs_parses_as_rust() {
        let src = lib_rs(&slug("svc"));
        let err = syn::parse_file(&src).err();
        assert!(err.is_none(), "lib.rs must be valid Rust: {err:?}");
    }

    #[test]
    fn test_lib_rs_carries_routes_splice_region() {
        let src = lib_rs(&slug("svc"));
        assert!(src.contains("// @generated:begin routes"));
        assert!(src.contains("// @generated:end routes"));
    }

    #[test]
    fn test_lib_rs_carries_module_decls_region() {
        let src = lib_rs(&slug("svc"));
        assert!(src.contains("// @generated:begin module_decls"));
        assert!(src.contains("// @generated:end module_decls"));
    }

    #[test]
    fn test_errors_rs_parses_as_rust() {
        let src = errors_rs();
        let err = syn::parse_file(&src).err();
        assert!(err.is_none(), "errors.rs must be valid Rust: {err:?}");
    }

    #[test]
    fn test_errors_rs_contains_app_error_and_into_response() {
        let src = errors_rs();
        assert!(src.contains("pub enum AppError"));
        assert!(src.contains("impl IntoResponse for AppError"));
        assert!(src.contains("StatusCode::NOT_FOUND"));
        assert!(src.contains("StatusCode::BAD_REQUEST"));
        assert!(src.contains("StatusCode::INTERNAL_SERVER_ERROR"));
    }
}
