//! `main.rs` + `lib.rs` scaffolding for generated user-projects.
//!
//! These are the entry-point files every user-project ships with — the
//! studio doesn't expect users to author them, but they live OUTSIDE
//! `@generated` regions (with the exception of the route-mount block
//! inside `lib.rs::router`) so users can extend startup behaviour with
//! their own middleware, env wiring, or graceful-shutdown logic.
//!
//! ## What's generated vs user-editable
//!
//! - `main.rs`: 100% generated. If the user wants startup hooks (e.g. a
//!   different listener config), they wrap `<crate>::router()` themselves
//!   in a separate binary; the studio's `main.rs` is a known-good default.
//! - `lib.rs`: skeleton is generated (module decls, the `router()` fn
//!   signature). The body of `router()` carries a `@generated:begin
//!   routes / @generated:end routes` region into which the `http.route`
//!   template splices `.route(...)` lines. Everything else in `lib.rs` is
//!   user-editable.
//!
//! ## No-panic discipline
//!
//! Generated `main.rs` uses `expect` only on unrecoverable startup
//! conditions (listener bind, server start). Consistent with the studio's
//! CLAUDE.md two-codebase rule applied to the generated side.

use crate::projects::Slug;

/// Generate the canonical `main.rs` for a user-project. Pure text; no
/// `@generated` regions (the whole file is regenerated each pass).
///
/// `spawn_tasks` is a list of Rust expressions that each evaluate to a
/// `Future<Output = ()>`. They are wrapped in `supervise()` and spawned
/// after the HTTP server is bound but before it is awaited.
pub fn main_rs(
    slug: &Slug,
    spawn_tasks: &[(String, String)],
    framework: &str,
    workers: Option<usize>,
    max_connections: Option<usize>,
    keep_alive_seconds: Option<u64>,
) -> String {
    let crate_name = slug.as_str().replace('-', "_");

    let spawn_lines = if spawn_tasks.is_empty() {
        String::new()
    } else {
        let mut s = "\n    // Long-running tasks\n".to_string();
        for (name, expr) in spawn_tasks {
            s.push_str(&format!(
                "    tokio::spawn(supervise(\"{name}\", || {expr}));\n"
            ));
        }
        s
    };

    let supervise_fn = if spawn_tasks.is_empty() {
        String::new()
    } else {
        r#"

/// Supervisor: restart a long-running task on panic with capped
/// exponential backoff.
async fn supervise<F, Fut>(name: &'static str, mut factory: F)
where
    F: FnMut() -> Fut + Send + 'static,
    Fut: std::future::Future<Output = ()> + Send + 'static,
{
    let mut backoff = std::time::Duration::from_secs(1);
    loop {
        tracing::info!(task = name, "starting");
        let task = tokio::spawn(factory());
        match task.await {
            Ok(()) => {
                tracing::warn!(task = name, "exited cleanly; restarting");
                backoff = std::time::Duration::from_secs(1);
            }
            Err(_) => {
                tracing::error!(task = name, "panicked; restarting after {:?} backoff", backoff);
                tokio::time::sleep(backoff).await;
                backoff = std::cmp::min(backoff * 2, std::time::Duration::from_secs(60));
            }
        }
    }
}
"#
        .to_string()
    };

    if framework == "actix" {
        let workers_line = if let Some(w) = workers {
            format!("\n        .workers({})", w)
        } else {
            String::new()
        };
        let conn_line = if let Some(c) = max_connections {
            format!("\n        .max_connections({})", c)
        } else {
            String::new()
        };
        let ka_line = if let Some(ka) = keep_alive_seconds {
            format!("\n        .keep_alive(std::time::Duration::from_secs({}))", ka)
        } else {
            String::new()
        };

        format!(
            r#"//! Generated by rust_no_code studio. This file is fully regenerated
//! on every `POST /api/projects/{slug}/regen` call.

#[actix_web::main]
async fn main() -> std::io::Result<()> {{
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    {crate_name}::debug::init_debug();

    let addr = std::env::var("BIND_ADDR").unwrap_or_else(|_| "127.0.0.1:8080".to_string());
    tracing::info!(%addr, "{crate_name} listening via actix-web");

    let mut server = actix_web::HttpServer::new(move || {{
        actix_web::App::new()
            .configure({crate_name}::configure_routes)
    }}){workers_line}{conn_line}{ka_line};{spawn_lines}

    server.bind(&addr)?.run().await
}}
{supervise_fn}
"#,
            slug = slug.as_str(),
            crate_name = crate_name,
            workers_line = workers_line,
            conn_line = conn_line,
            ka_line = ka_line,
            spawn_lines = spawn_lines,
            supervise_fn = supervise_fn,
        )
    } else if framework == "none" {
        // Pure background daemon (Kafka consumer, Scheduled jobs)
        let rt_setup = if let Some(w) = workers {
            format!(
                r#"fn main() {{
    let mut builder = tokio::runtime::Builder::new_multi_thread();
    builder.worker_threads({w});
    builder.enable_all();
    let rt = builder.build().expect("failed to build runtime");
    rt.block_on(async_main());
}}"#
            )
        } else {
            r#"#[tokio::main]
async fn main() {
    async_main().await;
}"#
            .to_string()
        };

        format!(
            r#"//! Generated by rust_no_code studio. This file is fully regenerated
//! on every `POST /api/projects/{slug}/regen` call.

{rt_setup}

async fn async_main() {{
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    {crate_name}::debug::init_debug();
    tracing::info!("{crate_name} background daemon active");{spawn_lines}

    // Wait for shutdown signal since there is no HTTP server blocking main
    tokio::signal::ctrl_c().await.expect("failed to listen for ctrl-c");
    tracing::info!("{crate_name} background daemon shutting down");
}}
{supervise_fn}
"#,
            slug = slug.as_str(),
            crate_name = crate_name,
            rt_setup = rt_setup,
            spawn_lines = spawn_lines,
            supervise_fn = supervise_fn,
        )
    } else {
        // Axum framework
        if let Some(w) = workers {
            format!(
                r#"//! Generated by rust_no_code studio. This file is fully regenerated
//! on every `POST /api/projects/{slug}/regen` call.

fn main() {{
    let mut builder = tokio::runtime::Builder::new_multi_thread();
    builder.worker_threads({workers});
    builder.enable_all();
    let rt = builder.build().expect("failed to build runtime");
    rt.block_on(async_main());
}}

async fn async_main() {{
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    {crate_name}::debug::init_debug();

    let addr = std::env::var("BIND_ADDR").unwrap_or_else(|_| "127.0.0.1:8080".to_string());
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .expect("failed to bind listener");
    tracing::info!(%addr, "{crate_name} listening");

    let app = {crate_name}::router();
    let server = axum::serve(listener, app);{spawn_lines}
    server.await.expect("server crashed");
}}
{supervise_fn}
"#,
                slug = slug.as_str(),
                crate_name = crate_name,
                workers = w,
                spawn_lines = spawn_lines,
                supervise_fn = supervise_fn,
            )
        } else {
            format!(
                r#"//! Generated by rust_no_code studio. This file is fully regenerated
//! on every `POST /api/projects/{slug}/regen` call.

#[tokio::main]
async fn main() {{
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    {crate_name}::debug::init_debug();

    let addr = std::env::var("BIND_ADDR").unwrap_or_else(|_| "127.0.0.1:8080".to_string());
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .expect("failed to bind listener");
    tracing::info!(%addr, "{crate_name} listening");

    let app = {crate_name}::router();
    let server = axum::serve(listener, app);{spawn_lines}
    server.await.expect("server crashed");
}}
{supervise_fn}
"#,
                slug = slug.as_str(),
                crate_name = crate_name,
                spawn_lines = spawn_lines,
                supervise_fn = supervise_fn,
            )
        }
    }
}

/// Generate the canonical `errors.rs` for a user-project.
///
/// Introduced in Section 7. Provides a minimal `AppError` enum using
/// `thiserror` and an Axum `IntoResponse` impl so that handlers and
/// services can return `Result<T, AppError>` out of the box.
///
/// This file is fully regenerated each pass (no `@generated` regions in
/// v1) because error variants are typically appended, not replaced, and
/// the studio does not yet support mergeable error definitions.
pub fn errors_rs(framework: &str) -> String {
    if framework == "actix" {
        r#"//! Application-level errors for this generated project.
//!
//! This file is fully regenerated on each `POST /api/projects/:slug/regen`.

use actix_web::http::StatusCode;
use actix_web::ResponseError;
use thiserror::Error;

/// The canonical error type returned by handlers and services.
#[derive(Debug, Error)]
pub enum AppError {
    #[error("not found")]
    NotFound,
    #[error("bad request: {0}")]
    BadRequest(String),
    #[error("internal server error")]
    Internal,
}

impl ResponseError for AppError {
    fn status_code(&self) -> StatusCode {
        match self {
            AppError::NotFound => StatusCode::NOT_FOUND,
            AppError::BadRequest(_) => StatusCode::BAD_REQUEST,
            AppError::Internal => StatusCode::INTERNAL_SERVER_ERROR,
        }
    }
}
"#
        .to_string()
    } else if framework == "none" {
        r#"//! Application-level errors for this generated project.
//!
//! This file is fully regenerated on each `POST /api/projects/:slug/regen`.

use thiserror::Error;

/// The canonical error type returned by handlers and services.
#[derive(Debug, Error)]
pub enum AppError {
    #[error("not found")]
    NotFound,
    #[error("bad request: {0}")]
    BadRequest(String),
    #[error("internal server error")]
    Internal,
}
"#
        .to_string()
    } else {
        r#"//! Application-level errors for this generated project.
//!
//! This file is fully regenerated on each `POST /api/projects/:slug/regen`.
//! To add custom error variants, edit this file or manage in a separate module.

use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use thiserror::Error;

/// The canonical error type returned by handlers and services.
#[derive(Debug, Error)]
pub enum AppError {
    #[error("not found")]
    NotFound,
    #[error("bad request: {0}")]
    BadRequest(String),
    #[error("internal server error")]
    Internal,
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let (status, body) = match self {
            AppError::NotFound => (StatusCode::NOT_FOUND, self.to_string()),
            AppError::BadRequest(_) => (StatusCode::BAD_REQUEST, self.to_string()),
            AppError::Internal => (StatusCode::INTERNAL_SERVER_ERROR, self.to_string()),
        };
        (status, body).into_response()
    }
}
"#
        .to_string()
    }
}

/// Generate the `debug.rs` debugger bridge scaffold.
pub fn debug_rs() -> String {
    r#"//! Synchronous Step-Debugger & Performance Profiling Bridge (S13 & S21).
//!
//! Handles visual breakpoints, interactive play/pause/step triggers,
//! edge payload logging, and dynamic latency/throughput profiling.

use std::sync::{Mutex, OnceLock};
use std::collections::HashMap;
use std::time::Instant;

/// Global thread-safe map to track visual node entry times.
fn start_times() -> &'static Mutex<HashMap<String, Instant>> {
    static LOCK: OnceLock<Mutex<HashMap<String, Instant>>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Initialize the debugger. No-op since we read stdin synchronously.
pub fn init_debug() {}

/// Helper to check if a breakpoint is configured on a node.
fn is_breakpoint(node_id: &str) -> bool {
    if let Ok(bps) = std::env::var("STUDIO_BREAKPOINTS") {
        bps.split(',').any(|s| s.trim() == node_id)
    } else {
        false
    }
}

/// Helper to check if global step-mode is active.
fn is_step_mode() -> bool {
    std::env::var("STUDIO_STEP_MODE").as_deref() == Ok("1")
}

/// Hook called BEFORE a visual node executes its core body.
pub fn bridge_before(node_id: &'static str, val: &dyn std::fmt::Debug) {
    // S21: Low-overhead profile gating
    if std::env::var("STUDIO_DEBUG").is_err() && std::env::var("STUDIO_PROFILE").is_err() {
        return;
    }

    // Capture entry time
    let now = Instant::now();
    if let Ok(mut lock) = start_times().lock() {
        lock.insert(node_id.to_string(), now);
    }

    // S13: Visual debugger suspension (only executes if STUDIO_DEBUG is active)
    if std::env::var("STUDIO_DEBUG").is_ok() {
        let formatted_val = format!("{:?}", val);
        
        // Broadcast variables for dynamic visual edge hovers
        println!("__studio_debug__:{{\"node_id\": \"{}\", \"state\": \"before\", \"value\": {:?}}}", node_id, formatted_val);

        let bp = is_breakpoint(node_id);
        let step = is_step_mode();

        if bp || step {
            // Broadcast that we have suspended execution
            println!("__studio_debug__:{{\"node_id\": \"{}\", \"state\": \"paused\", \"value\": {:?}}}", node_id, formatted_val);

            // Read command synchronously from stdin (blocks execution thread until studio backend sends newline command)
            let mut line = String::new();
            loop {
                line.clear();
                if std::io::stdin().read_line(&mut line).is_ok() {
                    let cmd = line.trim();
                    if cmd == "resume" || cmd == "step" {
                        if cmd == "step" {
                            std::env::set_var("STUDIO_STEP_MODE", "1");
                        } else {
                            std::env::set_var("STUDIO_STEP_MODE", "0");
                        }
                        break;
                    }
                } else {
                    break;
                }
            }
        }
    }
}

/// Hook called AFTER a visual node executes its core body.
pub fn bridge_after(node_id: &'static str, val: &dyn std::fmt::Debug) {
    if std::env::var("STUDIO_DEBUG").is_err() && std::env::var("STUDIO_PROFILE").is_err() {
        return;
    }

    // S21: Compute execution latency in microseconds and emit standard print
    if let Ok(mut lock) = start_times().lock() {
        if let Some(start) = lock.remove(node_id) {
            let elapsed = start.elapsed().as_micros();
            println!("__studio_profile__:{{\"node_id\": \"{}\", \"latency_us\": {}}}", node_id, elapsed);
        }
    }

    // S13: Emits dynamic debug state after execution completes
    if std::env::var("STUDIO_DEBUG").is_ok() {
        let formatted_val = format!("{:?}", val);
        println!("__studio_debug__:{{\"node_id\": \"{}\", \"state\": \"after\", \"value\": {:?}}}", node_id, formatted_val);
    }
}
"#
    .to_string()
}


/// Generate the `lib.rs` scaffold. The empty `@generated:begin routes`
/// region is the splice point T7's `http.route` template targets.
pub fn lib_rs(slug: &Slug, framework: &str) -> String {
    let crate_name = slug.as_str().replace('-', "_");
    if framework == "actix" {
        r#"//! Generated by rust_no_code studio. The module declarations and the
//! `configure_routes()` function are regenerated each pass; user-edited code is
//! preserved outside the `@generated` regions.

#![allow(dead_code, unused_imports, unused_variables)]

// @generated:begin module_decls
// @generated:end module_decls

/// Actix-web router configuration. Spliced from `http.route` visual nodes.
pub fn configure_routes(cfg: &mut actix_web::web::ServiceConfig) {
    // @generated:begin routes
    // @generated:end routes
}
"#
        .to_string()
    } else if framework == "none" {
        r#"//! Generated by rust_no_code studio. The module declarations are regenerated each pass;
//! user-edited code is preserved outside the `@generated` regions.

#![allow(dead_code, unused_imports, unused_variables)]

// @generated:begin module_decls
// (Filled by codegen — module declarations live here.)
// @generated:end module_decls
"#
        .to_string()
    } else {
        r#"//! Generated by rust_no_code studio. The module declarations and the
//! `router()` function are regenerated each pass; user-edited code is
//! preserved outside the `@generated` regions.

#![allow(dead_code, unused_imports, unused_variables)]

// @generated:begin module_decls
// (Filled by codegen — module declarations live here.)
// @generated:end module_decls

/// HTTP router for this user-project. Routes mounted here are spliced
/// from `http.route` template emissions; add additional `.layer(...)`
/// middleware outside the `@generated:routes` region and your edits will
/// survive regen.
pub fn router() -> axum::Router {
    let mut r = axum::Router::new();
    // @generated:begin routes
    // (Filled by codegen — `.route(...)` calls live here.)
    // @generated:end routes
    r
}
"#
        .to_string()
    }
}

/// Generate the project contract `CLAUDE.md` for a user-project.
///
/// Kept in sync with the studio's offline pair-programming guidelines so
/// that LLMs/agents working on this generated project know how to compile,
/// test, and follow architectural boundaries.
pub fn claude_md(slug: &crate::projects::types::Slug) -> String {
    let crate_name = slug.as_str().replace('-', "_");
    let mut s = String::new();
    s.push_str("# ");
    s.push_str(&crate_name);
    s.push_str(" - Visual Rust Project Contract\n\n");
    s.push_str("This generated project is managed by 'rust_no_code' studio. You can edit this project directly, but please respect the boundaries between generated and user-editable code.\n\n");
    s.push_str("## Build and Test Commands\n");
    s.push_str("- Check code: 'cargo check'\n");
    s.push_str("- Build release: 'cargo build --release'\n");
    s.push_str("- Run tests: 'cargo test'\n");
    s.push_str("- Run project: 'cargo run' (or set 'BIND_ADDR=127.0.0.1:8080 cargo run')\n\n");
    s.push_str("## Project Conventions & Structure\n");
    s.push_str("- Fully generated files: These are completely overwritten on regeneration. Do not edit them directly as your changes will be lost on the next canvas save/check:\n");
    s.push_str("  - 'Cargo.toml' (managed dependencies)\n");
    s.push_str("  - 'src/main.rs' (supervised runners and axum listener)\n");
    s.push_str("  - 'src/types/*.rs' (generated struct/enum models)\n");
    s.push_str("  - 'src/functions/*.rs' (generated async functions)\n");
    s.push_str("  - 'src/schedulers/*.rs' (cron schedulers)\n");
    s.push_str("  - 'src/consumers/*.rs' (file tails, queues)\n");
    s.push_str("  - 'src/integrations/*.rs' (HTTP clients, SQLite writers)\n");
    s.push_str("- User-editable files / regions:\n");
    s.push_str("  - 'src/lib.rs': Spliced routes are inside '// @generated:begin routes' and '// @generated:end routes'. You can add custom middleware, Axum layers, or custom modules outside this region!\n");
    s.push_str("  - 'src/errors.rs': Customize application-level errors.\n\n");
    s.push_str("## Coding Guidelines\n");
    s.push_str("- Async First: All handlers, services, and integrations use 'async/await'.\n");
    s.push_str("- Error Handling: Prefer propagating errors via Axum-compatible 'Result<T, AppError>' and the '?' operator. Avoid 'unwrap()', 'expect()', or 'panic!' unless absolutely unrecoverable.\n");
    s.push_str("- Tokio Runtime: Leverage tokio primitives (like MPSC, Broadcast, Sleep, Spawn) inside your custom nodes.\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn slug(s: &str) -> Slug {
        Slug::new(s).unwrap()
    }

    #[test]
    fn test_claude_md_renders_correctly() {
        let src = claude_md(&slug("user-service"));
        assert!(src.contains("# user_service - Visual Rust Project Contract"), "found:\n{src}");
        assert!(src.contains("cargo check"));
        assert!(src.contains("cargo test"));
    }

    #[test]
    fn test_main_rs_parses_as_rust() {
        let src = main_rs(&slug("user-service"), &[], "axum", None, None, None);
        let err = syn::parse_file(&src).err();
        assert!(err.is_none(), "main.rs must be valid Rust: {err:?}");
    }

    #[test]
    fn test_main_rs_references_crate_name_with_dashes_replaced() {
        let src = main_rs(&slug("user-service"), &[], "axum", None, None, None);
        assert!(src.contains("user_service::router()"));
        assert!(!src.contains("user-service::router()"));
    }

    #[test]
    fn test_main_rs_with_spawn_tasks_includes_supervise() {
        let tasks = vec![(
            "orders-consumer".to_string(),
            "crate::consumers::orders::run()".to_string(),
        )];
        let src = main_rs(&slug("svc"), &tasks, "axum", None, None, None);
        assert!(src.contains("async fn supervise"), "supervise helper must be present");
        assert!(src.contains("tokio::spawn(supervise(\"orders-consumer\""));
        assert!(src.contains("crate::consumers::orders::run()"));
        assert!(syn::parse_file(&src).is_ok(), "main.rs with spawns must parse");
    }

    #[test]
    fn test_main_rs_without_spawn_tasks_omits_supervise() {
        let src = main_rs(&slug("svc"), &[], "axum", None, None, None);
        assert!(!src.contains("async fn supervise"));
    }

    #[test]
    fn test_lib_rs_parses_as_rust() {
        let src = lib_rs(&slug("svc"), "axum");
        let err = syn::parse_file(&src).err();
        assert!(err.is_none(), "lib.rs must be valid Rust: {err:?}");
    }

    #[test]
    fn test_lib_rs_carries_routes_splice_region() {
        let src = lib_rs(&slug("svc"), "axum");
        assert!(src.contains("// @generated:begin routes"));
        assert!(src.contains("// @generated:end routes"));
    }

    #[test]
    fn test_lib_rs_carries_module_decls_region() {
        let src = lib_rs(&slug("svc"), "axum");
        assert!(src.contains("// @generated:begin module_decls"));
        assert!(src.contains("// @generated:end module_decls"));
    }

    #[test]
    fn test_errors_rs_parses_as_rust() {
        let src = errors_rs("axum");
        let err = syn::parse_file(&src).err();
        assert!(err.is_none(), "errors.rs must be valid Rust: {err:?}");
    }

    #[test]
    fn test_errors_rs_contains_app_error_and_into_response() {
        let src = errors_rs("axum");
        assert!(src.contains("pub enum AppError"));
        assert!(src.contains("impl IntoResponse for AppError"));
        assert!(src.contains("StatusCode::NOT_FOUND"));
        assert!(src.contains("StatusCode::BAD_REQUEST"));
        assert!(src.contains("StatusCode::INTERNAL_SERVER_ERROR"));
    }
}
