//! Cargo.toml builder for generated user-projects.
//!
//! Produces a deterministic `Cargo.toml` from the project slug + the
//! aggregated dependency hints templates emitted during this regen pass.
//!
//! ## Dep-merge policy
//!
//! - **Baseline** deps ([`baseline_dependencies`]) are always present —
//!   `tokio`, `axum`, `serde`, `serde_json`, `tracing`,
//!   `tracing-subscriber`, `thiserror`, `anyhow`. These match the studio
//!   itself, so codegen-flavour parity holds between studio code and
//!   generated user-project code (see `CLAUDE.md` two-codebase rule).
//! - **Template-hinted** deps come from each `RuntimeEmission.dependencies`
//!   the templates returned. Deduplicated by crate name; baseline wins on
//!   conflict.
//! - Output ordering is sorted by crate name so two regens on the same
//!   graph produce byte-identical files (the determinism property the
//!   region merger relies on).

use std::collections::BTreeMap;

use crate::projects::Slug;

/// Crate-name → version-requirement string. Used both for the baseline
/// table and for the merge result.
type DepMap = BTreeMap<String, String>;

/// The deps every generated user-project ships with, regardless of which
/// templates appear in the graph. Matches the studio's own dep set so
/// the no-panic / no-blocking / tracing-everywhere discipline is
/// achievable in generated code without per-template plumbing.
pub fn baseline_dependencies() -> DepMap {
    let mut m = BTreeMap::new();
    m.insert("tokio".into(), r#"{ version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }"#.into());
    m.insert("axum".into(), "\"0.7\"".into());
    m.insert("serde".into(), r#"{ version = "1", features = ["derive"] }"#.into());
    m.insert("serde_json".into(), "\"1\"".into());
    m.insert("tracing".into(), "\"0.1\"".into());
    m.insert(
        "tracing-subscriber".into(),
        r#"{ version = "0.3", features = ["env-filter", "fmt"] }"#.into(),
    );
    m.insert("thiserror".into(), "\"1\"".into());
    m.insert("anyhow".into(), "\"1\"".into());
    m
}

/// Render a `Cargo.toml` for the project. `extra_deps` is the aggregated
/// template hints — duplicates against the baseline lose silently
/// (baseline wins; cargo's resolver decides actual versions at build
/// time).
pub fn render(slug: &Slug, extra_deps: &[(String, String)]) -> String {
    let mut deps = baseline_dependencies();
    for (name, version) in extra_deps {
        deps.entry(name.clone()).or_insert_with(|| {
            // Quote bare versions like "1.2" — table-form values
            // (starting with `{`) come pre-quoted from the template.
            if version.starts_with('{') || version.starts_with('"') {
                version.clone()
            } else {
                format!("\"{version}\"")
            }
        });
    }

    let mut out = String::new();
    out.push_str("# Generated by rust_no_code studio. Do not edit by hand —\n");
    out.push_str("# regenerate via POST /api/projects/<slug>/regen.\n\n");
    out.push_str("[package]\n");
    out.push_str(&format!("name = \"{}\"\n", slug.as_str().replace('-', "_")));
    out.push_str("version = \"0.1.0\"\n");
    out.push_str("edition = \"2021\"\n");
    out.push_str("publish = false\n\n");

    out.push_str("[lib]\n");
    out.push_str(&format!("name = \"{}\"\n", slug.as_str().replace('-', "_")));
    out.push_str("path = \"src/lib.rs\"\n\n");

    out.push_str("[[bin]]\n");
    out.push_str(&format!("name = \"{}\"\n", slug.as_str().replace('-', "_")));
    out.push_str("path = \"src/main.rs\"\n\n");

    out.push_str("[dependencies]\n");
    for (name, version) in &deps {
        out.push_str(&format!("{name} = {version}\n"));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn slug(s: &str) -> Slug {
        Slug::new(s).unwrap()
    }

    #[test]
    fn test_baseline_render_is_deterministic() {
        let a = render(&slug("svc"), &[]);
        let b = render(&slug("svc"), &[]);
        assert_eq!(a, b);
    }

    #[test]
    fn test_render_includes_baseline_deps() {
        let out = render(&slug("svc"), &[]);
        for crate_name in &["tokio", "axum", "serde", "tracing", "thiserror"] {
            assert!(
                out.contains(&format!("{crate_name} = ")),
                "baseline must include {crate_name}: {out}"
            );
        }
    }

    #[test]
    fn test_extra_deps_merged_unless_conflicting_with_baseline() {
        let extras = vec![
            ("rdkafka".to_string(), "0.36".to_string()),
            ("tokio".to_string(), "1.99".to_string()), // conflict — baseline wins
        ];
        let out = render(&slug("svc"), &extras);
        assert!(out.contains("rdkafka = \"0.36\""));
        // Baseline tokio entry has table form — confirm it survived.
        assert!(out.contains("tokio = { version = \"1\""));
        assert!(!out.contains("tokio = \"1.99\""));
    }

    #[test]
    fn test_dash_in_slug_becomes_underscore_in_crate_name() {
        let out = render(&slug("user-service"), &[]);
        assert!(out.contains("name = \"user_service\""));
        // The slug itself (with dashes) must NOT appear as the package
        // name — Cargo crates can't have dashes in `name`.
        assert!(!out.contains("name = \"user-service\""));
    }

    #[test]
    fn test_lib_and_bin_both_present() {
        let out = render(&slug("svc"), &[]);
        assert!(out.contains("[lib]"));
        assert!(out.contains("[[bin]]"));
    }
}
